version: "3.9"

services:
  feature_extractor:
    build:
      context: .
      dockerfile: deployment/Dockerfile.fe
    ports:
      - "8001:8001"
    networks:
      - phishnet

  inference_engine:
    build:
      context: .
      dockerfile: deployment/Dockerfile.inf
    depends_on:
      - feature_extractor
    ports:
      - "8002:8002"
    networks:
      - phishnet

  prometheus:
    image: prom/prometheus
    volumes:
      - ./dashboard/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - phishnet

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./dashboard/grafana/provisioning:/etc/grafana/provisioning
      - ./dashboard/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - phishnet

networks:
  phishnet:
    driver: bridge
