FROM python:3.10-slim

WORKDIR /app

COPY inference_engine/ ./inference_engine/
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
COPY model/phish_clf.joblib model/phish_clf.joblib

CMD ["uvicorn", "inference_engine.app:app", "--host", "0.0.0.0", "--port", "8002"]
