FROM python:3.10-slim

WORKDIR /app

COPY feature_extractor/ ./feature_extractor/
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "feature_extractor.server:app", "--host", "0.0.0.0", "--port", "8001"]
